### ISSUE TITLE
pgquarrel segfaults when db connection is unavailable

### ISSUE THREAD

**Issue by devrimgunduz** [eulerto/pgquarrel#91] opened 2020-04-02 09:38 UTC
pgquarrel segfaults when at least one db connection is unavailable (in this case, db instance on port 5411 is not running)

-bash-5.0$ pgquarrel --source-port=5412 --target-port=5411
Segmentation fault (core dumped)

I think it should throw an error saying that it cannot connect.

**Comment by eulerto** [comment] 2020-04-03 03:27
I couldn't reproduce. Could you provide a backtrace or `pgquarrel -v -v --source-port=5412 --target-port=5411`?

BTW, I fixed a similar bug (commit 552fe30db4f97528ff15b90aef5b9afdd50832ce). It wasn't included in pgquarrel `0.7.0`, although it will be included in `0.8.0`. Are you testing master?

**Closed** 2020-10-12 15:07 UTC
